name: Run Tests with DB in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for DB to be ready..."
          while ! docker exec ${{ job.services.db.id }} pg_isready -U test_user; do
            sleep 5
          done
      
      - name: Create .env file
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=test_user" >> .env
          echo "DB_PASS=test_password" >> .env
          echo "DB_NAME=test_db" >> .env
          echo "DB_NAME_TEST=test_db" >> .env

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint
      
      - name: Format
        run: make format
           
      - name: Tests
        run: |
          make test